server:
  servlet:
    context-path: /v1
  port: 6000

spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://account-mysql:3306/account
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
