version: '3'
services:
  eureka:
    build: ./eureka
    ports:
      - 8761:8761

  account:
    build: ./account
    ports:
      - 6000:6000
    depends_on:
      - account-mysql

  account-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: account
    ports:
      - 3306:3306