version: '3.7'
services:
  eureka:
    container_name: eureka
    build: ./eureka
    ports:
      - 8761:8761

  service:
    container_name: service
    build: ./service
    ports:
      - 8080:8080

  auth-service:
    container_name: auth
    build: ./auth-service
    ports:
      - 5000:5000