version: '3'
services:
  eureka:
    build: ./eureka
    ports:
      - 8761:8761

  account:
    build: ./account
    ports:
      - 6000:6000
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - account-mysql

  account-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306

  tbd:
    build: ./tbd
    ports:
      - 7000:7000

  zuul:
    build: ./zuul
    ports:
      - 8080:8080