version: '3'
services:
  eureka:
    build: ./eureka
    ports:
      - 8761:8761

  auth:
    build: ./auth
    ports:
      - 5000:5000
    depends_on:
      - auth-mysql

  auth-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: admin
    ports:
      - 3306:3306

  account:
    build: ./account
    ports:
      - 6000:6000