server:
  port: 8080

spring:
  application:
    name: service

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true