server:
  port: 8080

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 15000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

zuul:
  ignoredServices: '*'
  routes:
    tbd:
      path: /tbd/**
      serviceId: tbd

    item-service:
      path: /items/**
      serviceId: item-service

    web-service:
      path: /**
      serviceId: web-service