server:
  port: 8080

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  ignoredServices: '*'
  routes:
    tbd:
      path: /tbd/**
      serviceId: tbd
      stripPrefix: false
      sensitiveHeaders: