server:
  port: 5000

spring:
  application:
    name: auth
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:mysql://auth-mysql:3306/admin
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true