server:
  port: 8080

spring:
  application:
    name: tbd

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true